name: Docker Build & Push

on:
  push:
    branches: [ "main" ]
    paths:  # 仅当Dockerfile或相关文件变化时触发
      - 'Dockerfile'
      - '​**​/Dockerfile'
      - 'docker/​**​'
env:
  REGISTRY: ghcr.io  # 镜像名称规范：ghcr.io/<GITHUB_OWNER>/<REPO_NAME>
  IMAGE_NAME: ${{ github.repository }} 
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 推送镜像到GitHub Registry时需要

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          # 使用自动生成的GITHUB_TOKEN认证（无需手动配置secrets）
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          cache-from: type=gha  # 启用GitHub缓存
          cache-to: type=gha,mode=max
